import{useEffect,useState,type ReactNode}from'react';
import{Link,NavLink,useNavigate}from'react-router-dom';
import{Activity,Bell,BrainCircuit,BriefcaseBusiness,CreditCard,Database,LayoutDashboard,LogOut,Settings,ShieldCheck,Users,FileText,UserCircle,Search,Workflow,type LucideIcon}from'lucide-react';
import{useAuth}from'./auth';
import{homeFor}from'./navigation';
import{request}from'./api';

function WorkspaceSwitcher(){const[items,setItems]=useState<any[]>();useEffect(()=>{request<any[]>('/workspaces').then(setItems)},[]);if(!items?.length)return null;const active=items.find(item=>item.active)?.organization.id||items[0].organization.id;async function change(id:string){await request('/workspace/switch',{method:'POST',body:JSON.stringify({organization_id:id})});window.location.assign('/employer')}return <label className="workspace-switcher"><span>WORKSPACE</span><select value={active} onChange={e=>change(e.target.value)}>{items.map(item=><option value={item.organization.id} key={item.organization.id}>{item.organization.name} · {item.role}</option>)}</select></label>}

export function useWorkspacePermissions(enabled=true){const[permissions,setPermissions]=useState<string[]>();useEffect(()=>{if(enabled)request<any>('/workspace').then(data=>setPermissions(data.membership.permissions)).catch(()=>setPermissions([]));else setPermissions([])},[enabled]);return permissions}

export function Logo(){const{user}=useAuth();const nav=useNavigate();const openHome=()=>nav(homeFor(user));return <div className="logo logo-link" role="link" tabIndex={0} aria-label="SmartHire home" onClick={openHome} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openHome()}}}><span className="logo-mark">S</span><span>SmartHire</span></div>}
export function Spinner(){return <div className="spinner" aria-label="Loading"/>}
export function Empty({title,body}:{title:string;body:string}){return <div className="empty"><Search size={34}/><h3>{title}</h3><p>{body}</p></div>}

export function Shell({children}:{children:ReactNode}){
  const{user,logout}=useAuth();const nav=useNavigate();const permissions=useWorkspacePermissions(user?.role==='employer');if(!user)return null;
  const employerLinks=([['/employer','Dashboard',LayoutDashboard],['/employer/jobs','My Jobs',BriefcaseBusiness,'analytics.view'],['/employer/jobs/new','Post a Job',FileText,'jobs.manage'],['/employer/pipeline','Hiring Pipeline',Workflow,'analytics.view'],['/employer/team','Recruiter Team',Users,'analytics.view'],['/employer/intelligence','AI Scorecards',BrainCircuit,'jobs.manage'],['/employer/settings','Workspace & Billing',CreditCard,'organization.manage']] as [string,string,LucideIcon,string?][]).filter(([, , ,permission])=>!permission||permissions?.includes(permission)).map(([to,label,Icon])=>[to,label,Icon] as [string,string,LucideIcon]);
  const links:[string,string,LucideIcon][]=user.role==='employer'?employerLinks:user.role==='applicant'?[['/applicant/jobs','Job Board',BriefcaseBusiness],['/applicant/applications','My Applications',FileText]]:[['/admin','System Dashboard',LayoutDashboard],['/admin/users','User Management',Users],['/admin/jobs','Job Postings',BriefcaseBusiness]];
  return <div className={`app-shell ${user.role==='employer'&&permissions&&!permissions.includes('candidates.manage')?'workspace-readonly':''}`}><aside><Logo/>{user.role==='employer'&&<WorkspaceSwitcher/>}<nav>{links.map(([to,label,Icon])=><NavLink key={String(to)} to={String(to)} end={to==='/employer'||to==='/admin'}><Icon size={18}/>{String(label)}</NavLink>)}<NavLink to="/notifications"><Bell size={18}/>Notifications</NavLink><NavLink to="/profile"><UserCircle size={18}/>Profile</NavLink></nav><button className="logout" onClick={async()=>{await logout();nav('/login')}}><LogOut size={18}/>Logout</button></aside><main><header className="topbar"><div><strong>Welcome back, {user.full_name.split(' ')[0]}!</strong><small>Here’s what’s happening today.</small></div><div className="account"><ShieldCheck size={18}/><span>{user.role}</span></div></header><div className="content">{children}</div></main></div>
}

export function AdminShell({children}:{children:ReactNode}){
  const{user,logout}=useAuth();const nav=useNavigate();if(!user)return null;
  const links=[['/admin','Command Center',Activity],['/admin/users','Identity & Access',Users],['/admin/jobs','Content Control',BriefcaseBusiness],['/admin/intelligence','Intelligence Monitor',Database],['/admin/operations','Operations & Audit',Settings],['/admin/saas','SaaS Accounts',CreditCard],['/admin/saas/requests','Plan Requests',Bell],['/admin/governance','Configuration',Settings],['/notifications','Notifications',Bell]];
  return <div className="admin-shell"><aside className="admin-rail"><Link className="admin-brand" to="/admin" aria-label="Admin Control Center home"><span><ShieldCheck/></span><div><strong>SmartHire</strong><small>CONTROL CENTER</small></div></Link><div className="admin-environment"><i/>LOCAL ENVIRONMENT</div><nav>{links.map(([to,label,Icon])=><NavLink key={String(to)} to={String(to)} end={to==='/admin'||to==='/admin/saas'}><Icon size={18}/><span>{String(label)}</span></NavLink>)}</nav><div className="admin-operator"><div className="admin-avatar">{user.full_name.slice(0,2).toUpperCase()}</div><div><strong>{user.full_name}</strong><small>Platform administrator</small></div></div><button className="admin-logout" onClick={async()=>{await logout();nav('/admin/login')}}><LogOut size={17}/>Secure sign out</button></aside><main><header className="admin-topbar"><div><span>ADMINISTRATION</span><strong>Platform Operations</strong></div><div className="admin-health"><i/>All systems operational</div></header><div className="admin-content">{children}</div></main></div>
}

export function Stat({label,value,accent='blue'}:{label:string;value:string|number;accent?:string}){return <div className={`stat ${accent}`}><div className="stat-icon"><BriefcaseBusiness size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
export function Badge({children,tone='green'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
